# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# runs-on: carbonrunner-4vcpu-ubuntu-latest

name: CarbonRunner Test
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group-live # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
